version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis_db
    depends_on:
      - redis_db
    networks:
      - ml_network

  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge